### ISSUE TITLE
Won't run as expected

### ISSUE THREAD

**Issue by niikoo** [ozum/not-sync-cli#1]
```powershell
PS C:\Users\post\OneDrive> mkdir node_modules


    Directory: C:\Users\post\OneDrive


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23.03.2021     11:55                node_modules


PS C:\Users\post\OneDrive> not-sync node_modules
node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\ProgramData\nvm\v15.11.0\node_modules\package.json'
    at Object.openSync (node:fs:506:3)
    at Object.readFileSync (node:fs:402:35)
    at Object.<anonymous> (C:\ProgramData\nvm\v15.11.0\node_modules\not-sync-cli\dist\utils\pkg.js:5:35)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\ProgramData\nvm\v15.11.0\node_modules\not-sync-cli\dist\not-sync.js:30:31) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\ProgramData\\nvm\\v15.11.0\\node_modules\\package.json'
}
PS C:\Users\post\OneDrive>
```

**Comment by ozum** [comment]
Hi @niikoo,

I fixed the path to the `package.json` file. Could you please install v1.0.2

**Comment by niikoo** [comment]
Hi @ozum 
Maybe you should do the admin check first:
```bash
[not-sync]               > i info     CWD: C:\Users\niikoo\OneDrive
[not-sync] [oneDrive]    > i info     Will disable oneDrive sync for following paths:
                                      • .\node_modules\
[not-sync] [oneDrive]    > √ success  Moved: tranaas -> C:\Users\niikoo\OneDrive Linked Files\node_modules
Error: EPERM: operation not permitted, symlink '..\OneDrive Linked Files\node_modules' -> 'C:\Users\niikoo\OneDrive\node_modules'
```
So now, my files are just moved out of the directory, and no link was formed.

**Comment by ozum** [comment]
Hi @niikoo,

An extra hand will help a lot. Could you please give an example of how to check permission before files are moved?
